query Products($status: Boolean) {
  products(where: {status: {_eq: $status}}) {
    id_data
    jumlahBarang
    kodeBarang
    namaBarang
    hargaBarang
    satuan
    status
  }
}
query selectProduct($kode: String) {
  products(where: {_and: {kodeBarang: {_eq: $kode}}}) {
    id_data
  }
}
